server:
  port: 8005


spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 123.56.56.237
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        prefer-ip-address: true
        hostname: 127.0.0.1